config/routes.rb
Rails.application.routes.draw do
  
  get 'reservations/index'
  get 'informations/index'
  get 'informations/new'
  get 'clinics/index'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations' }, :skip => [:session]
  devise_scope :user do
    get "/", to: "devise/sessions#new", as: :new_user_session
    post "login", to: "devise/sessions#create", as: :user_session
    delete "logout", to: "devise/sessions#destroy", as: :destroy_user_session
    get "signup", to: "devise_invitable/registrations#new"
    post "signup", to: "devise_invitable/registrations#create"
    get "signup/cancel", to: "devise_invitable/registrations#cancel"
    get "user", to: "devise_invitable/registrations#edit"
    patch "user", to: "devise_invitable/registrations#update", as: nil
    put "user", to: "devise_invitable/registrations#update", as: :update_user_registration
    delete "user", to: "devise_invitable/registrations#destroy", as: :destroy_user_registration
    get "password", to: "devise/passwords#new"
    post "password", to: "devise/passwords#create"
    get "password/edit", to: "devise/passwords#edit"
    patch "password", to: "devise/passwords#update"
    put "password", to: "devise/passwords#update", as: :update_user_password
  end

  # devise_scope :user do
  #   get "/", to: "devise/sessions#destroy", as: :destroy_user_session
  # end

  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  namespace :staff do
    resources :reservations
    resources :clinics
    resources :informations
  end

  # namespace :staff do
  #   resources :informations
  #   resources :reservations,only: [:index]   
  #   resources :clinics do
  #     resource :reservation
  #   end
  # end

  namespace :client do
    resources :reservations, only: [:index]
    resources :clinics do
      resources :reservations
    end
  end

  resources :doctors
  resources :patients
  resources :reservations

end

app/models/clinic.rb
class Clinic < ApplicationRecord
  has_many :reservations, dependent: :destroy
  has_many :reservation_patients, through: :reservations, source: :patient
  has_many :informations, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  has_many :doctors
  mount_uploader :image, ImageUploader
  scope :name_address_search, -> (name_address_search) {
    next if name_address_search.blank?
    where(['name LIKE ? OR address LIKE ?', "%#{name_address_search}%", "%#{name_address_search}%" ])
  }
end

app/controllers/client/clinics_controller.rb
class Client::ClinicsController < ApplicationController
before_action :set_clinic, only: [:show, :edit, :update, :destroy]

  def index
    @clinics = Clinic.all.page(params[:page]).per(10)
    if params[:clinic].present?
      @clinics = Clinic.name_address_search(params[:clinic][:name_address_search]).page(params[:page]).per(10)
    end 
  end

  def show
    @reservations = current_user.patient.reservations
    @reservations = @reservations.recent.order(start: :asc)
    @reservations = @reservations.page(params[:page]).per(10)   
  end

  def destroy
    @reservations = current_user.patient.reservations
    @reservation = @reservations.find(params[:id])
    respond_to do |format|
      if @reservation.destroy
        format.html { redirect_to client_clinic_path (@clinic), notice: '予約をキャンセルしました' }
        format.json { render :index }
      else
        format.html { redirect_to client_clinic_path(@clinic), notice: '予約をキャンセルできませんでした。' }
        format.json { render :index }
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    @email = @user.email
  end

  
  private

  def set_clinic
    @clinic = Clinic.find(params[:id])
  end

  def clinic_params
    params.require(:clinic).permit(:name, :address, :phone_number, :image, :image_cache)
  end

end

app/controllers/client/reservations_controller.rb
class Client::ReservationsController < ApplicationController
  # def index
  #   if current_user.patient
  #     @events = Event.where(user_id: current_user)
  #   end
  # end

  before_action :set_clinic, only: [:show, :edit, :update, :destroy]
  before_action :set_js, only: [:show, :edit, :update, :destroy]

  def index
    @reservations = Reservation.all
    respond_to do |format|
      format.html # => 通常のURLの場合、index.html.erb が返される
      format.json { render json: @reservations } # URLが.jsonの場合、@products.to_json が返される
    end
  end

  def create
    @clinic = Clinic.find(params[:clinic_id])
    @reservation = @clinic.reservations.build(reservation_params)
    @reservation.patient = current_user.patient

    if @reservation.double_booking?
       @reservation.save
       redirect_to client_clinic_path(@clinic), notice: '作成しました'
    else
      redirect_to client_clinic_path(@clinic), notice: 'すでに予約が入っています。予約できませんでした。'
    end
  end

  def show
  end


  def edit
    @reservation = @clinic.reservations.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    @reservation.assign_attributes(reservation_params)
      if @reservation.double_booking?
        @reservation.update(reservation_params)
        redirect_to client_clinic_path(@clinic), notice: '編集しました'
      else
        @reservation = Reservation.find(params[:id])
        redirect_to client_clinic_path(@clinic), notice: 'すでに予約が入っています。編集できませんでした。'
      end
  end


  def destroy
    @reservation = Reservation.find(params[:id])
      if @reservation.destroy
        redirect_to client_clinic_path(@clinic), notice: '削除しました.'
      else
        redirect_to client_clinic_path(@clinic), notice: '削除できませんでした。' 
      end
  end

  private

  def set_clinic
    @clinic = Clinic.find(params[:clinic_id])
  end

  def reservation_params
    params.require(:reservation).permit(:start, :end_time)
  end

  def set_js
    gon.clinic_id = @clinic.id
  end
end

app/controllers/staff/clinics_controller.rb
class Staff::ClinicsController < ApplicationController
before_action :set_clinic, only: [:show, :edit, :update]

   def show
    @informations = @clinic.informations
    @reservations = @clinic.reservations.recent.order(start: :asc)
    @reservations = @reservations.page(params[:page]).per(10)
    if params[:sort_today]
      @reservations.each do |reservation| 
        if reservation.start.strftime("%Y-%m-%d") == DateTime.now.strftime("%Y-%m-%d")
          @reservations = []
          @reservations << reservation
        end
      end
      @reservations
    end
  end

  def edit
  end

  def update
    @clinic = Clinic.find(params[:id])
    if @clinic.update(clinic_params)
      redirect_to staff_clinic_path, notice: '編集しました'
    else
      render 'edit'
    end
  end

   def destroy
    @clinic = Clinic.find(current_user.doctor.clinic.id)
    @reservation = @clinic.reservations.find(params[:id])
    respond_to do |format|
      if @reservation.destroy
        format.html { redirect_to staff_clinic_path(@clinic), notice: '予約をキャンセルしました' }
        format.json { render :index }
      else
        format.html { redirect_to staff_clinic_path(@clinic), notice: '予約をキャンセルできませんでした。' }
        format.json { render :index }
      end
    end
  end

  private

  def set_clinic
    @clinic = Clinic.find(params[:id])
  end

  def clinic_params
    params.require(:clinic).permit(:name, :address, :phone_number, :image, :image_cache)
  end

  def information_params
    params.require(:information).permit(:comment)
  end

  
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/doctors/clinics_helper.rb
module Doctors::ClinicsHelper
end

app/helpers/patient/clinics_helper.rb
module Patient::ClinicsHelper
end

app/helpers/staff/clinics_helper.rb
module Staff::ClinicsHelper
end

app/views/client/clinics/index.html.erb
<h1><%= t('view.clinic_index') %></h1>

<%= form_with(model: Clinic.new, local: true, method: :get, url: client_clinics_path) do |form| %>

  <%= form.label :name_address, t("view.name_address_search") %>
  <%= form.search_field :name_address_search %>

  <%= form.submit t("view.search"), class:"btn btn-danger" %><br>
  <%= link_to t('view.undo'), client_clinics_path, class:"btn btn-primary" %>

 <table class="table table-bordered">
      <tr>
        <th><%= t('view.clinic_name') %></th>
        <th><%= t('view.address') %></th>
        <th><%= t('view.phone_number') %></th>
        <th><%= t('view.details') %></th>
      </tr>
    <% @clinics.each do |clinic| %>
      <tr>
        <td><%= clinic.name %></td>
        <td><%= clinic.address %></td>
        <td><%= clinic.phone_number %></td>
        <td><%= link_to  t('view.details'), client_clinic_path(clinic.id) %></td>
      </tr>
    <% end %>
    </table>
  <% end %>
  <%= paginate @clinics %>

    <%= link_to t('view.my_page'), patient_path(current_user.patient.id), class:"btn btn-primary" %>

app/views/client/clinics/show.html.erb
  <h1><%= image_tag @clinic.image.url %></h1><br>

<div class ="show_clinic">
  <table class="table table-bordered">
    <tr>
      <th><%= t("view.clinic_name")%></th>
      <td><%= @clinic.name %></td>
    </tr>
    <tr>
      <th><%= t("view.address")%></th>
      <td><%= @clinic.address %></td>
    </tr>
    <tr>
      <th><%= t("view.phone_number")%></th>
      <td><%= @clinic.phone_number %></td>
    </tr>
  </table><br>
  <table class="table table-bordered"><br>
      <tr>
        <h4><%= t('view.clinic_information') %></h4>
      </tr>
    <% @clinic.informations.each do |information| %>
      <tr>
        <td><%= information.comment %></td>
      </tr>
    <% end %>
  </table><br>

<div class=""><%= link_to "予約をする",  client_clinic_reservation_path(@clinic),id:"booking", class:"btn btn-primary" %></div>
<br>
<h4 id="patient_page"><%= current_user.patient.name %>さんの予約</h4>
<table class="table table-bordered">
  <tr>
    <th><%= t('view.clinic_name') %></th>
    <th><%= t('view.reservation_start') %></th>
    <th><%= t('view.edit') %></th>
    <th><%= t('view.destroy') %></th>
  </tr>
  <% @reservations.each do |reservation| %>
    <tr>
      <td><%= reservation.clinic.name %></td>
      <td><%= reservation.start.strftime("%Y-%m-%d %H:%M:%S") %></td>
      <td><%= link_to t("view.edit"), edit_client_clinic_reservation_path(@clinic,reservation.id), class:"btn btn-primary" %> </td>
      <td><%= link_to t('view.destroy'), client_clinic_reservation_path(@clinic,reservation.id), method: :delete, class:"btn btn-primary" %></td>
    </tr>
  <% end %>
</table>