config/routes.rb
Rails.application.routes.draw do
  
  get 'reservations/index'
  get 'informations/index'
  get 'informations/new'
  get 'clinics/index'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations' }, :skip => [:session]
  devise_scope :user do
    get "/", to: "devise/sessions#new", as: :new_user_session
    post "login", to: "devise/sessions#create", as: :user_session
    delete "logout", to: "devise/sessions#destroy", as: :destroy_user_session
    get "signup", to: "devise_invitable/registrations#new"
    post "signup", to: "devise_invitable/registrations#create"
    get "signup/cancel", to: "devise_invitable/registrations#cancel"
    get "user", to: "devise_invitable/registrations#edit"
    patch "user", to: "devise_invitable/registrations#update", as: nil
    put "user", to: "devise_invitable/registrations#update", as: :update_user_registration
    delete "user", to: "devise_invitable/registrations#destroy", as: :destroy_user_registration
    get "password", to: "devise/passwords#new"
    post "password", to: "devise/passwords#create"
    get "password/edit", to: "devise/passwords#edit"
    patch "password", to: "devise/passwords#update"
    put "password", to: "devise/passwords#update", as: :update_user_password
  end

  # devise_scope :user do
  #   get "/", to: "devise/sessions#destroy", as: :destroy_user_session
  # end

  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  namespace :staff do
    resources :reservations
    resources :clinics
    resources :informations
  end

  # namespace :staff do
  #   resources :informations
  #   resources :reservations,only: [:index]   
  #   resources :clinics do
  #     resource :reservation
  #   end
  # end

  namespace :client do
    resources :reservations, only: [:index]
    resources :clinics do
      resources :reservations
    end
  end

  resources :doctors
  resources :patients
  resources :reservations

end

app/models/clinic.rb
class Clinic < ApplicationRecord
  has_many :reservations, dependent: :destroy
  has_many :reservation_patients, through: :reservations, source: :patient
  has_many :informations, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  has_many :doctors
  mount_uploader :image, ImageUploader
  scope :name_address_search, -> (name_address_search) {
    next if name_address_search.blank?
    where(['name LIKE ? OR address LIKE ?', "%#{name_address_search}%", "%#{name_address_search}%" ])
  }
end

app/controllers/client/clinics_controller.rb
class Client::ClinicsController < ApplicationController
before_action :set_clinic, only: [:show, :edit, :update, :destroy]

  def index
    @clinics = Clinic.all.page(params[:page]).per(10)
    if params[:clinic].present?
      @clinics = Clinic.name_address_search(params[:clinic][:name_address_search]).page(params[:page]).per(10)
    end 
  end

  def show
    @reservations = current_user.patient.reservations
    @reservations = @reservations.recent.order(start: :asc)
    @reservations = @reservations.page(params[:page]).per(10)   
  end

  def destroy
    @reservations = current_user.patient.reservations
    @reservation = @reservations.find(params[:id])
    respond_to do |format|
      if @reservation.destroy
        format.html { redirect_to client_clinic_path (@clinic), notice: '予約をキャンセルしました' }
        format.json { render :index }
      else
        format.html { redirect_to client_clinic_path(@clinic), notice: '予約をキャンセルできませんでした。' }
        format.json { render :index }
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    @email = @user.email
  end

  
  private

  def set_clinic
    @clinic = Clinic.find(params[:id])
  end

  def clinic_params
    params.require(:clinic).permit(:name, :address, :phone_number, :image, :image_cache)
  end

end

app/controllers/staff/clinics_controller.rb
class Staff::ClinicsController < ApplicationController
before_action :set_clinic, only: [:show, :edit, :update]

   def show
    @informations = @clinic.informations
    @reservations = @clinic.reservations.recent.order(start: :asc)
    @reservations = @reservations.page(params[:page]).per(10)
    if params[:sort_today]
      @reservations.each do |reservation| 
        if reservation.start.strftime("%Y-%m-%d") == DateTime.now.strftime("%Y-%m-%d")
          @reservations = []
          @reservations << reservation
        end
      end
      @reservations
    end
  end

  def edit
  end

  def update
    @clinic = Clinic.find(params[:id])
    if @clinic.update(clinic_params)
      redirect_to staff_clinic_path, notice: '編集しました'
    else
      render 'edit'
    end
  end

   def destroy
    @clinic = Clinic.find(current_user.doctor.clinic.id)
    @reservation = @clinic.reservations.find(params[:id])
    respond_to do |format|
      if @reservation.destroy
        format.html { redirect_to staff_clinic_path(@clinic), notice: '予約をキャンセルしました' }
        format.json { render :index }
      else
        format.html { redirect_to staff_clinic_path(@clinic), notice: '予約をキャンセルできませんでした。' }
        format.json { render :index }
      end
    end
  end

  private

  def set_clinic
    @clinic = Clinic.find(params[:id])
  end

  def clinic_params
    params.require(:clinic).permit(:name, :address, :phone_number, :image, :image_cache)
  end

  def information_params
    params.require(:information).permit(:comment)
  end

  
end

app/controllers/staff/informations_controller.rb
class Staff::InformationsController < ApplicationController
  before_action :set_information, only: [:edit, :update, :destroy]


  def new
    @information = Information.new
  end

  def create
    @information = current_user.doctor.clinic.informations.new(information_params)
    if @information.save
      redirect_to staff_clinic_path(current_user.doctor.clinic.id), notice: 'お知らせを作成しました'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @information = Information.find(params[:id])
    if @information.update(information_params)
      redirect_to staff_clinic_path, notice: 'お知らせを編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @information.destroy
    redirect_to staff_clinic_path, notice:"お知らせを削除しました！"
  end

  private

  def set_information
    @information = Information.find(params[:id])
  end

  def information_params
    params.require(:information).permit(:comment)
  end

end

app/controllers/staff/reservations_controller.rb
class Staff::ReservationsController < ApplicationController

    before_action :set_clinic, only: [:show, :edit, :update, :destroy]

  def index
    @reservations = Reservation.all
    respond_to do |format|
      format.html # => 通常のURLの場合、index.html.erb が返される
      format.json { render json: @reservation } # URLが.jsonの場合、@products.to_json が返される
    end
  end

     
  def edit
    @reservation = @clinic.reservations.find(params[:id])
  end

  def update
    @reservation = @clinic.reservations.find(params[:id])
    @reservation.assign_attributes(reservation_params)
      if @reservation.double_booking?
        @reservation.update(reservation_params)
        redirect_to staff_clinic_path(@clinic), notice: '編集しました'
      else
        @reservation = Reservation.find(params[:id])
        redirect_to staff_clinic_path(@clinic), notice: 'すでに予約が入っています。編集できませんでした。'
      end
  end

  def show
    @reservations = @clinic.reservations
  end

  def edit
    @reservation = @clinic.reservations.find(params[:id])
  end

  def destroy
    @reservation = Reservation.find(params[:id])
      if @reservation.destroy
        redirect_to client_clinic_path(@clinic), notice: '削除しました.'
      else
        redirect_to client_clinic_path(@clinic), notice: '削除できませんでした。' 
      end
  end

  private

  def set_clinic
    @clinic = Clinic.find(current_user.doctor.clinic.id)
  end

  def reservation_params
    params.require(:reservation).permit(:start, :end_time)
  end
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/doctors/clinics_helper.rb
module Doctors::ClinicsHelper
end

app/helpers/patient/clinics_helper.rb
module Patient::ClinicsHelper
end

app/helpers/staff/clinics_helper.rb
module Staff::ClinicsHelper
end

app/helpers/staff/informations_helper.rb
module Staff::InformationsHelper
end

app/helpers/staff/reservations_helper.rb
module Staff::ReservationsHelper
end

app/views/staff/clinics/edit.html.erb
<div class="main-container ">
<h2><%= t('view.user_edit_page') %></h2>

<% if @clinic.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@clinic.errors.count, "error") %> prohibited this @clinic from being saved:</h2>
    <ul>
    <% @clinic.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @clinic, local: true, url: staff_clinic_path) do |f| %>

      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label :address %><br />
        <%= f.text_field :address %>
      </div>

      <div class="field">
        <%= f.label :phone_number %><br />
        <%= f.text_field :phone_number %>
      </div>

      <div class="field">
        <%= f.label :image %><br />
        <%= f.file_field :image %>
      </div>

    <div>
      <%= f.submit t('view.edit') %>
    </div>
<% end %>
<%= link_to t('view.my_page'), staff_clinic_path(@clinic.id), class:"btn btn-primary" %>
</div>

app/views/staff/clinics/show.html.erb
<br>
<div class ="show_clinic">
  <table class="table table-bordered">
    <tr>
      <th><%= t("view.clinic_name")%></th>
      <td><%= @clinic.name %></td>
    </tr>
    <tr>
      <th><%= t("view.address")%></th>
      <td><%= @clinic.address %></td>
    </tr>
    <tr>
      <th><%= t("view.phone_number")%></th>
      <td><%= @clinic.phone_number %></td>
    </tr>
  </table><br>
  <h4>予約状況</h4>
  <table class="table table-bordered">
  <tr>
    <th><%= t('view.name') %></th>
    <th><%= t('view.reservation_start') %></th>
    <th><%= t('view.edit') %></th>
    <th><%= t('view.destroy') %></th>
  </tr>
  <% @reservations.each do |reservation| %>
  <tbody>
    <tr>
      <td><%= reservation.patient.name %></td>
      <td><%= reservation.start.strftime("%Y年 %m月%d日 %H:%M") %></td>
      <td><%= link_to t("view.edit"), edit_staff_reservation_path(reservation.id,), class:"btn btn-primary" %> </td>
      <td><%= link_to t('view.destroy'), staff_clinic_path(reservation.id), method: :delete, class:"btn btn-primary" %></td>   
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "全ての予約を確認する", staff_clinic_path(start: :asc),class:"btn btn-info" %>
<%= link_to "本日の予約を確認する", staff_clinic_path(sort_today: "true"), class:"btn btn-info" %>
</div>
<div>
  <h1><%= image_tag @clinic.image.url %></h1>
</div> 
<div>
  <table class="table table-bordered">
    <tr>
      <th><%= t('view.notice') %></th>
      <th><%= t('view.edit') %></th>
      <th><%= t('view.destroy') %></th>
    </tr><br>
   <h4><%= t('view.clinic_information') %></h4>
    <% @informations.each do |information| %>

    <tr>
      <td><%= information.comment %></td>
      <td><%= link_to t('view.edit'), edit_staff_information_path(information.id), class:"btn btn-primary" %></td>
      <td><%= link_to t('view.destroy'), staff_information_path(information.id), method: :delete, class:"btn btn-primary" %></td>
    </tr>
    <% end %>
  </table>
</div>
<div class=''><%= link_to t('view.information_create'), new_staff_information_path, class:"btn btn-primary" %></div>
<div class=""><%= link_to t('view.edit'), edit_staff_clinic_path(current_user.doctor.clinic.id), class:"btn btn-primary" %></div>
<div class=""><%= link_to t('view.my_page'), doctor_path(current_user.doctor.id), class:"btn btn-primary" %></div>