config/routes.rb
Rails.application.routes.draw do
  
  get 'reservations/index'
  get 'informations/index'
  get 'informations/new'
  get 'clinics/index'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations' }, :skip => [:session]
  devise_scope :user do
    get "/", to: "devise/sessions#new", as: :new_user_session
    post "login", to: "devise/sessions#create", as: :user_session
    delete "logout", to: "devise/sessions#destroy", as: :destroy_user_session
    get "signup", to: "devise_invitable/registrations#new"
    post "signup", to: "devise_invitable/registrations#create"
    get "signup/cancel", to: "devise_invitable/registrations#cancel"
    get "user", to: "devise_invitable/registrations#edit"
    patch "user", to: "devise_invitable/registrations#update", as: nil
    put "user", to: "devise_invitable/registrations#update", as: :update_user_registration
    delete "user", to: "devise_invitable/registrations#destroy", as: :destroy_user_registration
    get "password", to: "devise/passwords#new"
    post "password", to: "devise/passwords#create"
    get "password/edit", to: "devise/passwords#edit"
    patch "password", to: "devise/passwords#update"
    put "password", to: "devise/passwords#update", as: :update_user_password
  end

  # devise_scope :user do
  #   get "/", to: "devise/sessions#destroy", as: :destroy_user_session
  # end

  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  namespace :staff do
    resources :reservations
    resources :clinics
    resources :informations
  end

  # namespace :staff do
  #   resources :informations
  #   resources :reservations,only: [:index]   
  #   resources :clinics do
  #     resource :reservation
  #   end
  # end

  namespace :client do
    resources :reservations, only: [:index]
    resources :clinics do
      resources :reservations
    end
  end

  resources :doctors
  resources :patients
  resources :reservations

end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :user
  belongs_to :clinic
  mount_uploader :image, ImageUploader
  enum gender: { 男: 0, 女: 1 }
  validates :name, presence: true, presence: {message: "入力してください"}
  validates :name_kana, presence: true, presence: {message: "入力してください"}
  validates :gender, presence: true
  validates :birthday, presence: true
  validates :phone_number, presence: true, presence: {message: "入力してください"}
  extend OrderAsSpecified
  scope :doctor_name_search, -> (name_search) {
    next if name_search.blank?
    where(['name LIKE ? OR name_kana LIKE ?', "%#{name_search}%","%#{name_search}%" ])
  }

  def self.revive_active_record(arr)
    ids = arr.map(&:id)
    Doctor.where(id: ids).order_as_specified(id: ids)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
before_action :set_doctor, only: [:show, :edit, :update, :destroy]


  def index
    @doctors = Doctor.all.sort{|d1, d2| d1.name_kana[0].casecmp(d2.name_kana[0])}
    @doctors = Doctor.revive_active_record(@doctors).page(params[:page]).per(10)
    if params[:doctor].present?
      @doctors = @doctors.doctor_name_search(params[:doctor][:name_search]).page(params[:page]).per(10)
    end 
  end
  
  def show
    @informations = @doctor.clinic.informations
  end

  def edit
    @email = @doctor.user.email
  end

  def update
    @doctor = Doctor.find(params[:id])
    @user = @doctor.user
    if @user.update(user_params) && @doctor.update(doctor_params)
      redirect_to doctor_path, notice: '編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path, notice:"治療家を削除しました！"
  end

  private

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:name, :name_kana, :gender, :birthday, :phone_number, :comment, :image, :image_cache, :admin)
  end

  def user_params
    params.require(:doctor).permit(:email, :password, :password_confirmation)
  end

  
end

app/helpers/doctors/clinics_helper.rb
module Doctors::ClinicsHelper
end

app/helpers/doctors/informations_helper.rb
module Doctors::InformationsHelper
end

app/helpers/doctors/reservations_helper.rb
module Doctors::ReservationsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/user/doctor_helper.rb
module User::DoctorHelper
end

app/views/doctors/edit.html.erb
<div class="main-container ">
<h2>ユーザ編集画面</h2>

<% if @doctor.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this @doctor from being saved:</h2>
    <ul>
    <% @doctor.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @doctor, local: true) do |f| %>      

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :name_kana %><br />
    <%= f.text_field :name_kana %>
  </div>

  <div class="field">
    <%= f.label :gender %><br />
    <%= f.select :gender, Doctor.genders.keys.to_a, {} %>
  </div>

  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday %>
  </div>

  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>

  <div>
    <%= f.submit t('view.update') %>
  </div>
<% end %>
<%= link_to t('view.my_page'), doctor_path(@doctor), class:"btn btn-primary" %>
</div>

app/views/doctors/index.html.erb
<h1><%=t("view.staff_index") %></h1><br>
<%= form_with(model: Doctor.new, local: true, method: :get) do |form| %>
  <%= form.label :doctor_name, t("view.name_name_kana_search") %>
  <%= form.search_field :name_search %>
  <%= form.submit t("view.search"), class:"btn btn-danger" %><br>
  
  <table class="table table-bordered">
    <tr>
      <th><%= t('view.name') %></th>
      <th><%= t('view.name_kana') %></th>
      <th><%= t('view.gender') %></th>
      <th><%= t('view.birthday') %></th>
      <th><%= t('view.admin') %></th>
      <th><%= t('view.details') %></th>
      <th><%= t('view.destroy') %></th>
    </tr>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.name_kana %></td>
        <td><%= doctor.gender %></td>
        <td><%= doctor.birthday %></td>
          <% if doctor.admin? %>
            <td><%= t('view.true') %></td>
          <% else %>
            <td><%= t('view.false') %></td>
          <% end %>
        <td><%= link_to t('view.details'), doctor_path(doctor.id) %></td>
        <td><%= link_to t('view.destroy'), doctor_path(doctor.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
      </tr>
    <% end %>
  </table>
  <%= paginate @doctors %>
  <%= link_to t('view.my_page'), doctor_path(current_user.doctor.id), class:"btn btn-primary" %>
<% end %>

app/views/doctors/show.html.erb
<h1><%= t('view.staff_my_page') %></h1>

 <table class="table table-bordered">
      <tr>
        <h4><%= t('view.clinic_information') %></h4>
      </tr>
    <% @informations.each do |information| %>
      <tr>
        <td><%= information.comment %></td>
      </tr>
    <% end %>
  </table>

<div class ="">
  <table class="table table-bordered">
    <tr>
      <th><%= t('view.name') %></th>
      <td><%= @doctor.name %></td>
    </tr>
    <tr>
      <th><%= t('view.gender') %></th>
      <td><%= @doctor.gender %></td>
    </tr>
    <tr>
      <th><%= t('view.birthday') %></th>
      <td><%= @doctor.birthday %></td>
    </tr>
    <tr>
      <th><%= t('view.phone_number') %></th>
      <td><%= @doctor.phone_number %></td>
    </tr>
    <tr>
      <th><%= t('view.qualification') %></th>
      <td><%= @doctor.qualification %></td>
    </tr>
    <tr>
      <th><%= t('view.comment') %></th>
      <td><%= @doctor.comment %></td>
    </tr>
    <tr>
      <th><%= t('view.admin') %></th>
        <% if current_user.doctor.admin == true %>
          <td><%= t('view.true') %></td>
        <% else %>
          <td><%= t('view.false') %></td>
        <% end %>
    </tr>
  </table>
</div>

  <div><%= link_to t("view.profile_edit"), edit_doctor_path(@doctor), class:"btn btn-primary" %></div>
  <div><%= link_to t("view.email_password_edit"), edit_user_registration_path(@doctor), class:"btn btn-primary" %></div>
  <div><%= link_to t("view.clinic_show"), staff_clinic_path(current_user.doctor.clinic.id), id:"clinic_show", class:"btn btn-primary" %></div>
  <div><%= link_to t("view.staff_index"), doctors_path,id:"staff_index",class:"btn btn-primary" %></div>
  <div><%= link_to t("view.patient_index"), patients_path, id:"patient_index",class:"btn btn-primary" %></div>