config/routes.rb
Rails.application.routes.draw do
  
  get 'reservations/index'
  get 'informations/index'
  get 'informations/new'
  get 'clinics/index'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations' }, :skip => [:session]
  devise_scope :user do
    get "/", to: "devise/sessions#new", as: :new_user_session
    post "login", to: "devise/sessions#create", as: :user_session
    delete "logout", to: "devise/sessions#destroy", as: :destroy_user_session
    get "signup", to: "devise_invitable/registrations#new"
    post "signup", to: "devise_invitable/registrations#create"
    get "signup/cancel", to: "devise_invitable/registrations#cancel"
    get "user", to: "devise_invitable/registrations#edit"
    patch "user", to: "devise_invitable/registrations#update", as: nil
    put "user", to: "devise_invitable/registrations#update", as: :update_user_registration
    delete "user", to: "devise_invitable/registrations#destroy", as: :destroy_user_registration
    get "password", to: "devise/passwords#new"
    post "password", to: "devise/passwords#create"
    get "password/edit", to: "devise/passwords#edit"
    patch "password", to: "devise/passwords#update"
    put "password", to: "devise/passwords#update", as: :update_user_password
  end

  # devise_scope :user do
  #   get "/", to: "devise/sessions#destroy", as: :destroy_user_session
  # end

  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  namespace :staff do
    resources :reservations
    resources :clinics
    resources :informations
  end

  # namespace :staff do
  #   resources :informations
  #   resources :reservations,only: [:index]   
  #   resources :clinics do
  #     resource :reservation
  #   end
  # end

  namespace :client do
    resources :reservations, only: [:index]
    resources :clinics do
      resources :reservations
    end
  end

  resources :doctors
  resources :patients
  resources :reservations

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConnectCircle</title>
     <%= Gon::Base.render_data %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <script src= "locale/ja.js"></script> %>
  </head>

  <body>
    <header>
    <div class="app_name"><%= link_to "ConnectCircl" %></div>
      <div class="header_manu">
        <% if user_signed_in? %>
          <% if current_user.doctor %>
            <div class='crrent_user'><%= t('view.user_name') %>：<%= current_user.doctor.name %></div>
            <div class='my_page'><%= link_to  t('view.my_page'), doctor_path(current_user.doctor.id) %></div>
            <% if current_user.doctor.admin == true %>
              <div class='doctor_create'><%= link_to t('view.staff_create'), new_user_registration_path %></div>
            <% end %>
            <div class='index'><%= link_to t('view.clinic_page'), staff_clinic_path(current_user.doctor.clinic.id) %></div>
            <div class='index'><%= link_to t('view.staff_index'), doctors_path %></div>
            <div class='index'><%= link_to t('view.patient_index'), patients_path %></div>
            <div class='information_create'><%= link_to t('view.information_create'), new_staff_information_path %></div>
          <% end %>
          <% if current_user.patient %>
            <div class='crrent_user'><%= t('view.user_name') %>:<%= current_user.patient.name %></div> 
            <div class='my_page'><%= link_to t('view.my_page'), patient_path(current_user.patient.id) %></div>
            <div class='clinic_page'><%= link_to t('view.clinic_index'), client_clinics_path %></div>
          <% end %>
          <div class='log_out'><%= link_to t('view.log_out'), destroy_user_session_path, method: :delete %>
        <% else %>
          <div class='sign_up'><%= link_to t('view.sign_up'),new_user_registration_path %></div>
          <div class='log_in'><%= link_to t('view.log_in'), new_user_session_path %></div>
        <% end %>
      </div>
    </div>
    </header>
    <main>
      <% if notice %>
        <p class="alert alert-notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-error"><%= alert %></p>
      <% end %>
        <%= yield %>
    </main>
    <footer>
      <div>
        <li>ConnectCircle</li>
        <li>© 2019 Copyright MATSUSE</li>
      </div>
    </footer>
  </body>
</html>